package com.redhat.gss.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.9-redhat-2
 * 2013-05-08T15:24:38.610-07:00
 * Generated source version: 2.4.9-redhat-2
 * 
 */
@WebServiceClient(name = "HelloWS", 
                  wsdlLocation = "file:/Users/klape/support/support-examples/jaxws/webServiceRefTest.war/WEB-INF/wsdl/hello.wsdl",
                  targetNamespace = "http://jaxws.gss.redhat.com/") 
public class HelloWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://jaxws.gss.redhat.com/", "HelloWS");
    public final static QName Hello = new QName("http://jaxws.gss.redhat.com/", "hello");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/klape/support/support-examples/jaxws/webServiceRefTest.war/WEB-INF/wsdl/hello.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/klape/support/support-examples/jaxws/webServiceRefTest.war/WEB-INF/wsdl/hello.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns HelloWSImpl
     */
    @WebEndpoint(name = "hello")
    public HelloWSImpl getHello() {
        return super.getPort(Hello, HelloWSImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWSImpl
     */
    @WebEndpoint(name = "hello")
    public HelloWSImpl getHello(WebServiceFeature... features) {
        return super.getPort(Hello, HelloWSImpl.class, features);
    }

}
