package com.redhat.gss.mtom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-patch-01
 * Wed Oct 31 23:13:37 CDT 2012
 * Generated source version: 2.2.12-patch-01
 * 
 */
 
@WebService
public interface FileServer {

    @WebResult(name = "return", targetNamespace = "", partName = "return")
    @WebMethod
    public void downloadFile(
        @WebParam(partName = "data", name = "dataType")
        FileDataType data
    ) throws Exception;
}
